# Help Outputs

This file displays the help output for all available commands by executing a bunch of runs.

The first step is to copy over the `run` directory from the `_for_testing` directory.

In [8]:
import os
from IPython.display import Markdown
from openad.app.global_var_lib import _repo_dir

success = %openad import './tests/_for_testing/test_files/sample.csv'
success_str = success.data
if "Import failed" in success_str:
    print("Please rename or delete your current `_runs` folder first.")
else:
    print("Successfully copied over _runs folder to your workspace.")

# To display separators
def sep():
    print("\n\n\n" + "- " * 60 + "\n\n\n")

Successfully copied over _runs folder to your workspace.

<br><br><br>

### Copy over test files

In [ ]:
%openad import './tests/_for_testing/test_files/sample.csv'
%openad import './tests/_for_testing/test_files/base_molecules.sdf'
%openad import './tests/_for_testing/test_files/base_molecules.csv'

<br><br><br>

## Display All OpenAD Help Outputs

If you run into problems, you can display the help outputs by category by uncommenting the individual runs below.

In [4]:
# Display all
%openad run help_all

# # Or display individual
# %openad run help_filesystem
# %openad run help_general
# %openad run help_gui
# %openad run help_help
# %openad run help_llm
# %openad run help_mmols
# %openad run help_mws
# %openad run help_runs
# %openad run help_smols
# %openad run help_util
# %openad run help_workspaces

`list files [ path ]` <br>
<span style="color: #ccc">-------------------</span> <br>
List al directories and files in your current workspace. <br>

`import '<file_path>'` <br>
<span style="color: #ccc">--------------------</span> <br>
Import a file into your current workspace. <br>

`move '<source_file>' to '<destination_path>' [ force ]` <br>
`copy '<source_file>' to '<destination_path>' [ force ]` <br>
<span style="color: #ccc">------------------------------------------------------</span> <br>
Copy or move a file from one location to another. <br>

When the destination path includes a filename, you will be prompted to rename it. <br>
Use the `force` option to overwrite the file without prompting.


## Working with paths
`foobar.csv`              A file in your current workspace <br>
`/Users/John/foobar.csv`  An absolute file path <br>
`./foobar.csv`            A file on your current working directory <br>
`~/Documents/foobar.csv`  A file in your home directory


## Examples
Copy a file from your workspace to your home directory: <br>
`copy 'my_molecules.sdf' to '~/'` <br>

Move and rename a file within your workspace: <br>
`move 'my_data/dataset.csv' to 'other_data/dataset-new.csv'` <br>

Copy a file from the filesystem to your workspace while renaming the file: <br>
`move '/Users/John/Documents/dataset.csv' to 'dataset-new.csv'` <br>



 i  <span style="color: #ccc">To see all available None commands, run `None`</span> <br>

`move '<source_file>' to '<destination_path>' [ force ]` <br>
`copy '<source_file>' to '<destination_path>' [ force ]` <br>
<span style="color: #ccc">------------------------------------------------------</span> <br>
Copy or move a file from one location to another. <br>

When the destination path includes a filename, you will be prompted to rename it. <br>
Use the `force` option to overwrite the file without prompting.


## Working with paths
`foobar.csv`              A file in your current workspace <br>
`/Users/John/foobar.csv`  An absolute file path <br>
`./foobar.csv`            A file on your current working directory <br>
`~/Documents/foobar.csv`  A file in your home directory


## Examples
Copy a file from your workspace to your home directory: <br>
`copy 'my_molecules.sdf' to '~/'` <br>

Move and rename a file within your workspace: <br>
`move 'my_data/dataset.csv' to 'other_data/dataset-new.csv'` <br>

Copy a file from the filesystem to your workspace while renaming the file: <br>
`move '/Users/John/Documents/dataset.csv' to 'dataset-new.csv'` <br>



 i  <span style="color: #ccc">To see all available None commands, run `None`</span> <br>

`remove '<filename>'` <br>
<span style="color: #ccc">-------------------</span> <br>
Remove a file from your current workspace. <br>

`open '<filename>'` <br>
<span style="color: #ccc">-----------------</span> <br>
Open a file in its designated OS application. <br>

Examples: <br>
- `open 'base_molecules.sdf'` <br>
- `open my_dataframe` <br>

`show '<filename>'` <br>
<span style="color: #ccc">-----------------</span> <br>
Open a file in the graphical user interface. <br>

Examples: <br>
- `show 'my_molecules.molset.json'` <br>
- `show 'my_molecules.sdf'` <br>
- `show 'my_data.csv'` <br>

`openad` <br>
<span style="color: #ccc">------</span> <br>
Display the openad splash screen. <br>

`get status` <br>
<span style="color: #ccc">----------</span> <br>
Display the currently selected workspace and toolkit. <br>

`display history ` <br>
<span style="color: #ccc">----------------</span> <br>
Display the last 30 commands run in your current workspace. <br>

`clear sessions` <br>
<span style="color: #ccc">--------------</span> <br>
Clear any other sessions that may be running. <br>

`launch gui` <br>
<span style="color: #ccc">----------</span> <br>
Launch the OpenAD GUI (graphical user interface). <br>

`restart gui` <br>
<span style="color: #ccc">-----------</span> <br>
Terminate and then restart the GUI server. <br>

`quit gui` <br>
<span style="color: #ccc">--------</span> <br>
Terminate the GUI server. <br>

Intro <br>
`demo hello world` <br>
`demo pp <definition> <input string>` <br>
`demo hello <planet_name> | <subject> | <subject>,<subject>,...` <br>
`demo output styles` <br>

`docs` <br>
<span style="color: #ccc">----</span> <br>
Open the documentation webpage. <br>

`tell me <how to do xyz>` <br>
<span style="color: #ccc">-----------------------</span> <br>
Ask your AI assistant how to do anything in OpenAD. <br>

`set llm  <language_model_name>` <br>
<span style="color: #ccc">------------------------------</span> <br>
Set the target language model name for the `tell me` command. <br>

`clear llm auth` <br>
<span style="color: #ccc">--------------</span> <br>
Clear the language model's authentication file. <br>

`show mmol|protein <fasta> | '<pdb_id>'` <br>
<span style="color: #ccc">--------------------------------------</span> <br>
Launch the molecule viewer in your browser to visualize your macromolecule and inspect its properties. <br>

Examples: <br>
- Show a protein by its PDBe ID: <br>
  `show mmol '2g64'` <br>

- Show a protein by its FASTA string: <br>
  `show protein MAKWVCKICGYIYDEDAGDPDNGISPGTKFEELPDDWVCPICGAPKSEFEKLED` <br>

`add molecule|mol <name> | <smiles> | <inchi> | <inchikey> | <cid> [ as '<name>' ] [ basic ] [ force ]` <br>
<span style="color: #ccc">-----------------------------------------------------------------------------------------------------</span> <br>
Add a molecule to your current molecule working set. <br>

Supported molecule identifiers: <br>
- `name` / `synonym` <br>
- `SMILES` <span style="color: #ccc">- supports [ basic ]</span> <br>
- `InChI` <span style="color: #ccc">- supports [ basic ]</span> <br>
- `InChIKey` <br>
- `PubChem CID` <br>

Options: <br>
- `as <name>`: Provide a custom name for the molecule, which will be used by the software whenever refering to it going forward. <br>
  Note: you can always update a molecule's name later by running `rename molecule <name>`. <br>
- `basic`: Create a minimal molecule without enriching it with PubChem data. This is only relevant when using a SMILES or InChI string as identifier. Because no API calls are made, this is much faster than the default behavior. <br>
- `force`: Suppress the confirmation step before adding a molecule, which may be desired in batch operations. <br>

Notes: <br>
- You can use the 'mol' shorthand instead of 'molecule'. <br>
- If the requested molecule exists in your current working set or in memory, that version will be prioritized. <br>

Examples: <br>
- Add a molecule by SMILES string: <br>
  `add molecule CC(=O)OC1=CC=CC=C1C(=O)O` <br>

- Add a molecule by SMILES string, without enriching it with PubChem data: <br>
  `add molecule CC(=O)OC1=CC=CC=C1C(=O)O basic` <br>

- Add a molecule by SMILES string, giving it a custom name: <br>
  `add molecule CC(=O)OC1=CC=CC=C1C(=O)O as 'mymol' basic` <br>

- Add a molecule by unquoted InChI string: <br>
  `add mol InChI=1S/C9H8O4/c1-6(10)13-8-5-3-2-4-7(8)9(11)12/h2-5H,1H3,(H,11,12)` <br>

- Add a molecule by quoted InChI string: <br>
  `add mol 'InChI=1S/C9H8O4/c1-6(10)13-8-5-3-2-4-7(8)9(11)12/h2-5H,1H3,(H,11,12)'` <br>

- Add a molecule by InChIKey: <br>
  `add mol BSYNRYMUTXBXSQ-UHFFFAOYSA-N` <br>

- Add a molecule by InChIKey, giving it a custom name: <br>
  `add mol BSYNRYMUTXBXSQ-UHFFFAOYSA-N as 'mymol'` <br>

- Add a molecule by name: <br>
  `add molecule aspirin` <br>

- Add a molecule by name, supressing the confirmation step: <br>
  `add molecule aspirin force` <br>

- Add a molecule by quoted name: <br>
  `add mol 'Aspirin 325 mg'` <br>

- Add a molecule by its PubChem CID: <br>
  `add mol 2244` <br>

`remove molecule|mol <name> | <smiles> | <inchi> | <inchikey> | <cid> [ force ]` <br>
<span style="color: #ccc">------------------------------------------------------------------------------</span> <br>
Remove a molecule from the current working set based on a given molecule identifier. <br>

Supported molecule identifiers: <br>
- `name` / `synonym` <br>
- `SMILES` <br>
- `InChI` <br>
- `InChIKey` <br>
- `PubChem CID` <br>

Options: <br>
- `force`: Suppress the confirmation step before removing a molecule, which may be desired in batch operations. <br>

Notes: <br>
- You can use the 'mol' shorthand instead of 'molecule'. <br>

Examples: <br>
- Remove a molecule by name: <br>
  `remove molecule Aspirin` <br>

- Remove a molecule by SMILES: <br>
  `remove molecule CC(=O)OC1=CC=CC=C1C(=O)O` <br>

- Remove a molecule by InChIKey: <br>
  `remove mol BSYNRYMUTXBXSQ-UHFFFAOYSA-N` <br>

- Remove a molecule by InChI <br>
  `remove mol  InChI=1S/C9H8O4/c1-6(10)13-8-5-3-2-4-7(8)9(11)12/h2-5H,1H3,(H,11,12)` <br>

- Remove a molecule by CID: <br>
  `remove mol 2244` <br>

`list molecules|mols` <br>
<span style="color: #ccc">-------------------</span> <br>
List all molecules in the current working set. <br>

Notes: <br>
- You can use the 'mols' shorthand instead of 'molecules'. <br>

`show molecules|mols` <br>
<span style="color: #ccc">-------------------</span> <br>
Launch the molset viewer in your browser to visualize your molecule working set. <br>

Notes: <br>
- You can use the 'mols' shorthand instead of 'molecules'. <br>

`enrich molecules|mols with analysis` <br>
<span style="color: #ccc">-----------------------------------</span> <br>
Enrich the molecules in your current working set with the results of the last performed analysis. <br>

This assumes that your molecule working set contains either the input molecule or any of the result molecules from the analysis. <br>

Notes: <br>
- You can use the 'mols' shorthand instead of 'molecules'. <br>

Currently supported analysis commands: <br>

RXN: <br>
- `predict reaction` <br>
- `predict retrosynthesis` <br>

DS4SD: <br>
- `search for patents containing molecule` <br>
- `search for similiar molecules` <br>

Please refer to the DS4SD and RXN toolkits for further assistance on these commands. For example: <br>
`set context rxn` <br>
`predict reaction ?` <br>

`clear analysis cache` <br>
<span style="color: #ccc">--------------------</span> <br>
Clear the analysis results cache for your current workspace. <br>

Please refer to the `enrich molecules|mols with analysis` command for more information about analysis results. <br>

`display sources <name> | <smiles> | <inchi> | <inchikey> | <cid>` <br>
<span style="color: #ccc">----------------------------------------------------------------</span> <br>
Display the sources of a molecule's properties, attributing how they were calculated or where they were sourced. <br>

Supported molecule identifiers: <br>
- `name` / `synonym` <br>
- `SMILES` <br>
- `InChI` <br>
- `InChIKey` <br>
- `PubChem CID` <br>

Notes: <br>
- If the requested molecule exists in your current working set or in memory, that version will be prioritized. <br>

`rename molecule|mol <molecule_identifer_string> as <molecule_name>` <br>
<span style="color: #ccc">------------------------------------------------------------------</span> <br>
Rename a molecule in the current working set. <br>

Notes: <br>
- You can use the 'mol' shorthand instead of 'molecule'. <br>

Example: <br>
- Assuming you've added the molecule <span style="color: #dc0">CC(=O)OC1=CC=CC=C1C(=O)O</span> to your molecule working set, you can then rename it as such: <br>
  `rename molecule CC(=O)OC1=CC=CC=C1C(=O)O as Aspirin` <br>

<span style="color: #dc0">Commands starting with "load molecules"</span> <br>
- `load molecules|mols from file '<filename.molset.json|sdf|csv|smi>' [ enrich ] [ append ]` <br>
- `load molecules|mols from dataframe <dataframe> [ enrich ] [ append ]` <br>

<span style="color: #dc0">Commands starting with "load molecules"</span> <br>
- `load molecules|mols from file '<filename.molset.json|sdf|csv|smi>' [ enrich ] [ append ]` <br>
- `load molecules|mols from dataframe <dataframe> [ enrich ] [ append ]` <br>

`merge molecules|mols data from dataframe <dataframe> [ enrich ]` <br>
<span style="color: #ccc">---------------------------------------------------------------</span> <br>
Merge molecule data from a dataframe into the molecules in your working set. <br>

Options: <br>
- Append `enrich` to enrich the molecule with data from pubchem. <br>

The dataframe columns should be named as follows: <br>
- `subject` or `smiles`: molecules similes string <br>
- `property`: the name of the property to be merged <br>
- `result`: the value of the property to be nmerged <br>

Sample input file: <br>

 subject                                                               property                        result  <br>
 --------------------------------------------------------------------  -------------------------  -----------  <br>
 O=C(N)C(F)(OC(F)(F)C(F)(F)C(F)(F)F)C(F)(F)F                           molecular_weight               329.065  <br>
 O=C(O)C(F)(NC(F)(F)C(F)(F)C(F)(F)F)C(F)(F)F                           molecular_weight               329.065  <br>
 O=C(O)C(F)(OC(F)(F)C(F)(F)C)CF                                        molecular_weight               240.099  <br>
 O=C(O)C(F)(OC(O)(F)C(F)(F)C(F)(F)F)C(F)(F)F                           molecular_weight               328.058  <br>
 O=C(O)C(F)(OC(Cl)(F)C(F)(F)C(F)(F)F)C(F)(F)F                          molecular_weight               346.504  <br>
 O=C(O)C(F)(OC(F)(F)C(F)(O)C(F)(F)F)C(F)(F)F                           molecular_weight               328.058  <br>
 O=C(O)C(F)(OC(F)(O)C(F)(F)C(F)(F)F)C(F)(F)F                           molecular_weight               328.058  <br>
 O=C(O)C(F)(OC(F)(F)C(F)(Br)C(F)(F)F)C(F)(F)F                          molecular_weight               390.955  <br>
 O=C(O)C(F)OC(O)(F)C(F)(F)C(F)(F)F                                     molecular_weight               260.061  <br>

Notes: <br>
- You can use the 'mol' shorthand instead of 'molecule'. <br>

Examples: <br>
- Merge molecule data from a dataframe called `new_props`: <br>
  `merge molecules data from dataframe new_props` <br>

- Merge molecule data from a dataframe called `new_props`, while enriching the molecules with PubChem data: <br>
  `merge molecules data from dataframe new_props enrich` <br>

`export molecules|mols [ as '<filename.molset.json|sdf|csv|smi>' ]` <br>
<span style="color: #ccc">-----------------------------------------------------------------</span> <br>
Export your molecule working set as a file (CLI) or return it as a dataframe (Jupyter/API). <br>

Supported file formats: <br>
- molset (.molset.json) <br>
- SDF (.sdf) <br>
- CSV (.csv) <br>
- SMILES (.smi) <br>

Notes: <br>
- When exporting as a file, the filename's extension will define what format the molecule are exported as. <br>
- If no filename or extension is provided, the molecules will be saved as CSV file. <br>
- When run inside a Jupyter Notebook or from the API, the `as <filename>` clause will be ignored and a dataframe will be returned. <br>
- You can use the 'mols' shorthand instead of 'molecules'. <br>

`clear molecules|mols [ force ]` <br>
<span style="color: #ccc">------------------------------</span> <br>
Clear the molecule working set. <br>

Options: <br>
- `force`: Suppress the confirmation step before clearing the working set, which may be desired in batch operations. <br>

Notes: <br>
- You can use the 'mols' shorthand instead of 'molecules'. <br>

`create run` <br>
<span style="color: #ccc">----------</span> <br>
Start recording a run. <br>

`remove run <run_name>` <br>
<span style="color: #ccc">---------------------</span> <br>
remove a run. <br>

`save run as <run_name>` <br>
<span style="color: #ccc">----------------------</span> <br>
Stop recording a run and save it. <br>

## About Runs
A run is a prerecorded chain of commands that can be reused to automate certain workflows and avoid unnecessary repetition. <br>


Runs <br>
`create run` <br>
`remove run <run_name>` <br>
`save run as <run_name>` <br>
`run <run_name>` <br>
`list runs` <br>
`display run <run_name>` <br>

`list runs` <br>
<span style="color: #ccc">---------</span> <br>
List all runs saved in the current workspace. <br>

`display run <run_name>` <br>
<span style="color: #ccc">----------------------</span> <br>
Display the commands stored in a certain run. <br>

`display molecule|mol <name> | <smiles> | <inchi> | <inchikey> | <cid>` <br>
<span style="color: #ccc">---------------------------------------------------------------------</span> <br>
Display a molecule's details. <br>

A molecule's details include its identifiers, synonyms, properties and any analysis results it has been enriched with. <br>

Supported molecule identifiers: <br>
- `name` / `synonym` <br>
- `SMILES` <br>
- `InChI` <br>
- `InChIKey` <br>
- `PubChem CID` <br>

Notes: <br>
- You can use the 'mol' shorthand instead of 'molecule'. <br>
- If the requested molecule exists in your current working set or in memory, that version will be prioritized. <br>

Examples: <br>
- Display a molecule by name: <br>
  `display molecule Aspirin` <br>

- Display a molecule by SMILES string: <br>
  `display molecule CC(=O)OC1=CC=CC=C1C(=O)O` <br>

- Display a molecule by InChI string: <br>
  `display mol InChI=1S/C9H8O4/c1-6(10)13-8-5-3-2-4-7(8)9(11)12/h2-5H,1H3,(H,11,12)` <br>

- Display a molecule by InChIKey: <br>
  `display mol BSYNRYMUTXBXSQ-UHFFFAOYSA-N` <br>

- Display a molecule by its PubChem CID: <br>
  `display mol 2244` <br>

<span style="color: #dc0">Commands starting with "show molecule"</span> <br>
- `show molecule|mol <name> | <smiles> | <inchi> | <inchikey> | <cid>` <br>
- `show molecules|mols` <br>

`show molset|molecule-set '<molset_or_sdf_or_smi_path>' | using dataframe <dataframe>` <br>
<span style="color: #ccc">------------------------------------------------------------------------------------</span> <br>
Launch the molset viewer in your browser to visualize the contents of a molecule set. <br>

Examples: <br>
- `show molset 'neurotransmitters.mol.json'` <br>
- `show molset 'neurotransmitters.sdf'` <br>
- `show molset 'neurotransmitters.smi'` <br>
- `show molset my_dataframe` <br>

`@(<name> | <smiles> | <inchi> | <inchikey> | <cid>)>><molecule_property_name>` <br>
<span style="color: #ccc">-----------------------------------------------------------------------------</span> <br>
Request a molecule's property. <br>

Supported molecule identifiers: <br>
- `name` / `synonym` <br>
- `SMILES` <br>
- `InChI` <br>
- `InChIKey` <br>
- `PubChem CID` <br>

Notes: <br>
- In addition to a molecule's properties or identifiers, you can also request its synonyms. <br>
- If the requested molecule exists in your current working set or in memory, that version will be prioritized. <br>
- In addition to the properties listed below, you can also request any additional properties that are available in your molecule working set. <br>

Examples: <br>
- Obtain the molecular weight of a molecule known as Aspirin. <br>
  `@aspirin>>molecular_weight` <br>

- Obtain the canonical smiles string for the dopamine neurotransmitter. <br>
  `@dopamine>>canonical_smiles` <br>

- Obtain a molecules xlogp value using a SMILES string. <br>
  `@CC(=O)OC1=CC=CC=C1C(=O)O>>xlogp` <br>

- Obtain all the synonyms for ibuprofen. <br>
 `@ibuprofen>>synonyms` <br>

Available properties that can be queried: <br>
synonyms                                atom_stereo_count                       bond_stereo_count                        <br>
canonical_smiles                        charge                                  cid                                      <br>
complexity                              conformer_count_3d                      conformer_id_3d                          <br>
conformer_model_rmsd_3d                 conformer_rmsd_3d                       coordinate_type                          <br>
covalent_unit_count                     defined_atom_stereo_count               defined_bond_stereo_count                <br>
effective_rotor_count_3d                exact_mass                              feature_acceptor_count_3d                <br>
feature_anion_count_3d                  feature_cation_count_3d                 feature_count_3d                         <br>
feature_donor_count_3d                  feature_hydrophobe_count_3d             feature_ring_count_3d                    <br>
h_bond_acceptor_count                   h_bond_donor_count                      heavy_atom_count                         <br>
inchi                                   inchikey                                isomeric_smiles                          <br>
isotope_atom_count                      iupac_name                              mmff94_energy_3d                         <br>
mmff94_partial_charges_3d               molecular_formula                       molecular_weight                         <br>
molecular_weight_exact                  monoisotopic_mass                       multipoles_3d                            <br>
multipoles_3d                           pharmacophore_features_3d               pharmacophore_features_3d                <br>
rotatable_bond_count                    sol                                     sol_classification                       <br>
tpsa                                    undefined_atom_stereo_count             undefined_bond_stereo_count              <br>
volume_3d                               x_steric_quadrupole_3d                  xlogp                                    <br>
y_steric_quadrupole_3d                  z_steric_quadrupole_3d                  name                                     <br>
smiles                                  inchi                                   inchikey                                 <br>

<span style="color: #dc0">Commands starting with "export molecule"</span> <br>
- `export molecule|mol <name> | <smiles> | <inchi> | <inchikey> | <cid> [ as file ]` <br>
- `export molecules|mols [ as '<filename.molset.json|sdf|csv|smi>' ]` <br>

`display data '<filename.csv>'` <br>
<span style="color: #ccc">-----------------------------</span> <br>
Display data from a csv file. <br>

`display data -> result save [as '<filename.csv>']` <br>
<span style="color: #ccc">-------------------------------------------------</span> <br>
Save table data to csv file. <br>

`display data -> result open` <br>
<span style="color: #ccc">---------------------------</span> <br>
Explore table data in the browser. <br>

If you append `-d` to the end of the command `result open -d` display will result to data viewer. <br>

`display data -> result edit` <br>
<span style="color: #ccc">---------------------------</span> <br>
Edit table data in the browser. <br>

If you append `-d` to the end of the command `result open -d` display will result to data viewer. <br>

`display data -> result copy` <br>
<span style="color: #ccc">---------------------------</span> <br>
Copy table data to clipboard, formatted for spreadheet. <br>

`display data -> result display` <br>
<span style="color: #ccc">------------------------------</span> <br>
Display the result in Jupyter Notebook. <br>

If you append `-d` to the end of the command `result open -d` display will result to data viewer. <br>

`display data -> result as dataframe` <br>
<span style="color: #ccc">-----------------------------------</span> <br>
Return the result as dataframe (only for Jupyter Notebook). <br>

<span style="color: #d00">No commands starting with "<span style="color: #dc0">edit config</span>"</span> <br>

`set workspace <workspace_name>` <br>
<span style="color: #ccc">------------------------------</span> <br>
Change the current workspace. <br>

`get workspace [ <workspace_name> ]` <br>
<span style="color: #ccc">----------------------------------</span> <br>
Display details a workspace. When no workspace name is passed, details of your current workspace are displayed. <br>

`create workspace <workspace_name> [ description('<description>') on path '<path>' ]` <br>
<span style="color: #ccc">-----------------------------------------------------------------------------------</span> <br>
Create a new workspace with an optional description and path. <br>

`remove workspace <workspace_name> ` <br>
<span style="color: #ccc">----------------------------------</span> <br>
Remove a workspace from your registry. Note that this doesn't remove the workspace's directory. <br>

`list workspaces` <br>
<span style="color: #ccc">---------------</span> <br>
Lists all your workspaces. <br>

<br><br><br><br>

# Command Outputs

In [6]:
# %openad clear sessions

# # Display all
%openad run all

# # Or display individual
# %openad run filesystem
# %openad run general
# %openad run gui
# %openad run help
# %openad run llm
# %openad run mmols
# %openad run mws
# %openad run runs
# %openad run smols
# %openad run util
# %openad run workspaces

<span style="color: #d00">The selected file <span style="color: #dc0">/Users/themoenen/Local/GitHub/openad/tests/_for_testing/tests/_for_testing/test_files/base_molecules.sdf</span> does not exist</span> <br>

<span style="color: #dc0">Rename file from base_molecules.sdf to base_molecules-copy.sdf?</span> <br>

(y/n):  y

<span style="color: #dc0">The destination directory does not exist, create it?</span> <br>

(y/n):  y

<span style="color: #090">File saved to workspace as <span style="color: #dc0">test_files/base_molecules-copy.sdf</span></span> <br>

<span style="color: #dc0">Rename file from base_molecules.sdf to base_molecules-copy.sdf?</span> <br>

(y/n):  y

<span style="color: #dc0">The destination file already exists, overwrite?</span> <br>

(y/n):  y

<span style="color: #090">File saved to workspace as <span style="color: #dc0">test_files/base_molecules-copy.sdf</span></span> <br>

<span style="color: #dc0">Rename file from base_molecules.sdf to base_molecules-copy1.sdf?</span> <br>

(y/n):  y

<span style="color: #090">File saved to workspace as <span style="color: #dc0">test_files/base_molecules-copy1.sdf</span></span> <br>

<span style="color: #dc0">Rename file from base_molecules-copy.sdf to base_molecules-renamed.sdf?</span> <br>

(y/n):  y

<span style="color: #090">File saved to workspace as <span style="color: #dc0">test_files/base_molecules-renamed.sdf</span></span> <br>

<span style="color: #ffa500">Permanently deleting directory:</span> <br>
<span style="color: #ccc">/Users/themoenen/.openad/workspaces/DEFAULT/test_files</span> <br>

<span style="color: #dc0">Continue?</span> <br>

(y/n):  y

<span style="color: #090">Directory removed from workspace</span> <br>
<span style="color: #ccc">test_files</span> <br>

<span style="color: #ffa500">Permanently deleting file:</span> <br>
<span style="color: #ccc">/Users/themoenen/.openad/workspaces/DEFAULT/base_molecules.sdf</span> <br>

<span style="color: #dc0">Continue?</span> <br>

(y/n):  y

<span style="color: #090">File removed from workspace</span> <br>
<span style="color: #ccc">base_molecules.sdf</span> <br>

<pre>  ░░░░░░    ░░░░░░    ░░░░░░░░  ░░      ░░    ░░░░    ░░░░░░   <br>
░░      ░░  ░░    ░░  ░░        ░░░░    ░░  ░░    ░░  ░░    ░░ <br>
░░      ░░  ░░    ░░  ░░░░░░    ░░  ░░  ░░  ░░░░░░░░  ░░    ░░ <br>
░░      ░░  ░░░░░░    ░░        ░░    ░░░░  ░░    ░░  ░░    ░░ <br>
  ░░░░░░    ░░        ░░░░░░░░  ░░      ░░  ░░    ░░  ░░░░░░   <br>
</pre>

## Welcome to the Open Accelerated Discovery CLI

`intro`        If this is your first time, let us help you getting started. <br>

`? toolkits`   Learn about the toolkits. <br>

`?`            List all commands. <br>

...` ?`        List commands starting with "..." <br>

`? `...        List commands containing "..." <br>

`docs`         Read the docs in your browser. <br>

<span style="color: #dc0">Current workspace</span>: DEFAULT <br>
<span style="color: #dc0">Current context</span>: None <br>
<span style="color: #ccc">To see more details, run `get workspace` or `get context`.</span> <br>

<span style="color: #dc0">Terminate all other sessions? <br>
<span style="color: #ccc">Make sure you don't have any crucial processes running in other windows</span></span> <br>

(y/n):  y

<span style="color: #090">All sessions have been cleared</span> <br>

## Introduction to OpenAD

OpenAD is an intuitive toolkit that simplifies access to a variety of AI models and services for scientific discovery. Together with its convenient visualisation capabilities, OpenAD empowers scientists across industries to enhance their discovery process. <br>

OpenAD is designed to integrate into your existing workflows via Jupyter Notebook, CLI or API, using a low-code approach to accelerate your research. <br>

<a target="_blank" href="accelerate.science/projects/openad">accelerate.science/projects/openad</a>



### Molecule Working Set
Your molecule working set (MWS) is an in-memory list of small molecules that is the subject of your calculations and manipulations. <br>

The MWS makes it easy to gather candidate molecules from various sources, either by adding them individually, by loading them in batch from a dataframe, CSV or SDF file, or by bookmarking molecules in the GUI. You can then calculate certain properties, perform triage and then store the results in your workspace as a molecule set, ready for further processing within OpenAD or elsewhere. <br>

Please note that at this time the MWS does not support macromolecules, only small molecules. <br>

<span style="color: #ccc">To see how to work with your molecule working set, run `? mws`</span>



### Workspaces
Your workspace represents an isolated environment where your molecules, molecule sets and other files related to your research are stored. <br>

Each workspace has its own command history and corresponds with a directory stored in ~/openad/workspaces, allowing you to work on multiple isolated projects at once. OpenAD comes loaded with a default workspace called 'default', and you can create as many additional workspaces as needed. <br>

<span style="color: #ccc">To see how to work with workspaces, run `? workspace`</span>



### Plugins
Plugins provide drastically simplified access to a series of advanced tools, and make it easy for your own Python applications to interface with OpenAD. <br>

<span style="color: #ccc">To see how to work with plugins, run `? toolkit`</span>



### Runs
A run is a prerecorded chain of commands that can be reused to automate certain workflows and avoid unnecessary repetition. <br>

<span style="color: #ccc">To see how to work with runs, run `? run`</span> <br>

## Available Commands - Main

Macromolecules <br>
`show mmol|protein <fasta> | '<pdb_id>'` <br>

General <br>
`openad` <br>
`get status` <br>
`display history ` <br>
`clear sessions` <br>

Workspaces <br>
`set workspace <workspace_name>` <br>
`get workspace [ <workspace_name> ]` <br>
`create workspace <workspace_name> [ description('<description>') on path '<path>' ]` <br>
`remove workspace <workspace_name> ` <br>
`list workspaces` <br>

Toolkits <br>
`set context <toolkit_name> [ reset ]` <br>

Runs <br>
`create run` <br>
`remove run <run_name>` <br>
`save run as <run_name>` <br>
`run <run_name>` <br>
`list runs` <br>
`display run <run_name>` <br>

Utility <br>
`display data '<filename.csv>'` <br>
`result save [as '<filename.csv>']` <br>
`result open` <br>
`result edit` <br>
`result copy` <br>
`result display` <br>
`result as dataframe` <br>

GUI <br>
`launch gui` <br>
`restart gui` <br>
`quit gui` <br>

LLM <br>
`tell me <how to do xyz>` <br>
`set llm  <language_model_name>` <br>
`clear llm auth` <br>

File System <br>
`list files [ path ]` <br>
`import '<file_path>'` <br>
`move '<source_file>' to '<destination_path>' [ force ]` <br>
`copy '<source_file>' to '<destination_path>' [ force ]` <br>
`remove '<filename>'` <br>
`open '<filename>'` <br>
`show '<filename>'` <br>

Help <br>
`intro` <br>
`docs` <br>
`?` <br>
`? ...`   --> List all commands containing "..." <br>
`... ?`   --> List all commands starting with "..." <br>

Model <br>
`model auth list` <br>
`model auth add group <auth_group> with '<auth_token>'` <br>
`model auth remove group <auth_group>` <br>
`model auth add service <service_name> to group <auth_group>` <br>
`model auth remove service <service_name>` <br>
`model service status` <br>
`model service describe <service_name>` <br>
`model catalog list` <br>
`uncatalog model service <service_name>` <br>
`catalog model service from [ remote ] '<path>|<github>|<service_url>' as <service_name> USING (<parameter>=<value> <parameter>=<value>)` <br>
`model service up <service_name> [ no_gpu ]` <br>
`model service local up <service_name> [ no_gpu ]` <br>
`model service down <service_name>` <br>
`get model service <service_name> result '<result_id>'` <br>

Small Molecules <br>
`display molecule|mol <name> | <smiles> | <inchi> | <inchikey> | <cid>` <br>
`show molecule|mol <name> | <smiles> | <inchi> | <inchikey> | <cid>` <br>
`show molset|molecule-set '<molset_or_sdf_or_smi_path>' | using dataframe <dataframe>` <br>
`@(<name> | <smiles> | <inchi> | <inchikey> | <cid>)>><molecule_property_name>` <br>
`export molecule|mol <name> | <smiles> | <inchi> | <inchikey> | <cid> [ as file ]` <br>

Molecule Working Set <br>
`add molecule|mol <name> | <smiles> | <inchi> | <inchikey> | <cid> [ as '<name>' ] [ basic ] [ force ]` <br>
`remove molecule|mol <name> | <smiles> | <inchi> | <inchikey> | <cid> [ force ]` <br>
`list molecules|mols` <br>
`show molecules|mols` <br>
`enrich molecules|mols with analysis` <br>
`clear analysis cache` <br>
`display sources <name> | <smiles> | <inchi> | <inchikey> | <cid>` <br>
`rename molecule|mol <molecule_identifer_string> as <molecule_name>` <br>
`load molecules|mols from file '<filename.molset.json|sdf|csv|smi>' [ enrich ] [ append ]` <br>
`load molecules|mols from dataframe <dataframe> [ enrich ] [ append ]` <br>
`merge molecules|mols data from dataframe <dataframe> [ enrich ]` <br>
`export molecules|mols [ as '<filename.molset.json|sdf|csv|smi>' ]` <br>
`clear molecules|mols [ force ]` <br>



<span style="color: #dc0"> PLUGIN </span> Demo  <br>

<span style="color: #ccc">To learn more about this plugin, run `demo`</span> <br>

<span style="color: #ccc">|</span>    Language localization <br>
<span style="color: #ccc">|</span>    `demo localize a` <br>
<span style="color: #ccc">|</span>    `demo localize b` <br>
<span style="color: #ccc">|</span>     <br>
<span style="color: #ccc">|</span>    Intro <br>
<span style="color: #ccc">|</span>    `demo hello world` <br>
<span style="color: #ccc">|</span>    `demo pp <definition> <input string>` <br>
<span style="color: #ccc">|</span>    `demo hello <planet_name> | <subject> | <subject>,<subject>,...` <br>
<span style="color: #ccc">|</span>    `demo output styles` <br>
<span style="color: #ccc">|</span>     <br>
<span style="color: #ccc">|</span>    Molecules <br>
<span style="color: #ccc">|</span>    `demo validate mol <molecule_identifier>` <br>
<span style="color: #ccc">|</span>    `demo validate mols [<molecule_identifier>,<molecule_identifier>,...]` <br>
<span style="color: #ccc">|</span>    `demo visualize molecule <molecule_identifier> [ basic ]` <br>
<span style="color: #ccc">|</span>    `demo visualize molecules [<molecule_identifier>,<molecule_identifier>,...] [ basic ]` <br>



<span style="color: #dc0"> PLUGIN </span> Deep Search  <br>

<span style="color: #ccc">To learn more about this plugin, run `ds`</span> <br>

<span style="color: #ccc">|</span>    Molecules <br>
<span style="color: #ccc">|</span>    `ds search for molecules similar to <smiles> [ save as '<filename.csv>' ]` <br>
<span style="color: #ccc">|</span>    `ds search for molecules with substructure <smiles> [ save as '<filename.csv>' ]` <br>
<span style="color: #ccc">|</span>    `ds search for molecules in patents from file '<filename.csv>' [ save as '<filename.csv>' ]` <br>
<span style="color: #ccc">|</span>    `ds search for molecules in patents from list ['<patent_id>','<patent_id>',...] [ save as '<filename.csv>' ]` <br>
<span style="color: #ccc">|</span>    `ds search for molecules in patents from dataframe <dataframe_name> [ save as '<filename.csv>' ]` <br>
<span style="color: #ccc">|</span>     <br>
<span style="color: #ccc">|</span>    Collections <br>
<span style="color: #ccc">|</span>    `ds list all collections [ details ] [ save as '<filename.csv>' ]` <br>
<span style="color: #ccc">|</span>    `ds list all domains [ save as '<filename.csv>' ]` <br>
<span style="color: #ccc">|</span>    `ds list collections containing '<search_query>' [ save as '<filename.csv>' ]` <br>
<span style="color: #ccc">|</span>    `ds list collections for domain '<domain_name>' [ save as '<filename.csv>' ]` <br>
<span style="color: #ccc">|</span>    `ds list collections for domains ['<domain_name>','<domain_name>',...] [ save as '<filename.csv>' ]` <br>
<span style="color: #ccc">|</span>    `ds list collection details '<collection_name_or_key>'` <br>
<span style="color: #ccc">|</span>    `ds search collection '<collection_name_or_key>' for '<search_query>'` <br>
<span style="color: #ccc">|</span>    `    [ USING (<parameter>=<value> <parameter>=<value>) ] [ show (data | docs | data docs) ]` <br>
<span style="color: #ccc">|</span>    `    [ estimate only ] [ save as '<filename.csv>' ]` <br>
<span style="color: #ccc">|</span>     <br>
<span style="color: #ccc">|</span>    Patents <br>
<span style="color: #ccc">|</span>    `ds search for patents containing molecule <smiles>  [ save as '<filename.csv>' ]` <br>
<span style="color: #ccc">|</span>     <br>
<span style="color: #ccc">|</span>    System <br>
<span style="color: #ccc">|</span>    `ds login [ reset ]` <br>



<span style="color: #dc0"> PLUGIN </span> RXN  <br>

<span style="color: #ccc">To learn more about this plugin, run `rxn`</span> <br>

<span style="color: #ccc">|</span>    General <br>
<span style="color: #ccc">|</span>    `rxn list models [ save as '<filename.csv>' ]` <br>
<span style="color: #ccc">|</span>    `rxn interpret recipe '<recipe>' | '<recipe.txt>' ` <br>
<span style="color: #ccc">|</span>     <br>
<span style="color: #ccc">|</span>    System <br>
<span style="color: #ccc">|</span>    `rxn clear cache` <br>
<span style="color: #ccc">|</span>    `rxn login [ reset ]` <br>
<span style="color: #ccc">|</span>     <br>
<span style="color: #ccc">|</span>    Prediction <br>
<span style="color: #ccc">|</span>    `rxn predict retrosynthesis|retro <smiles> [ USING (<parameter>=<value> <parameter>=<value>) ] [ rich ] [ use cache ] [ return df ]` <br>
<span style="color: #ccc">|</span>    `rxn predict reaction <smiles>.<smiles> [ USING (ai_model='<ai_model>' topn=<integer>) ] [ rich ] [ use cache ]` <br>
<span style="color: #ccc">|</span>    `rxn predict reactions from list ['<smiles>.<smiles>',...] [ USING (ai_model='<ai_model>' topn=<integer>) ] [ rich ] [ use cache ]` <br>
<span style="color: #ccc">|</span>    `rxn predict reactions from file '<filename.csv>' [ USING (ai_model='<ai_model>' topn=<integer>) ] [ rich ] [ use cache ]` <br>
<span style="color: #ccc">|</span>    `rxn predict reactions from dataframe <dataframe_name> [ USING (ai_model='<ai_model>' topn=<integer>) ] [ rich ] [ use cache ]` <br>
<span style="color: #ccc">|</span>    `rxn predict topn reactions <smiles>.<smiles> [ USING (ai_model='<ai_model>' topn=<integer>) ] [ rich ] [ use cache ]` <br>
<span style="color: #ccc">|</span>    `rxn predict topn reactions from list ['<smiles>.<smiles>',...] [ USING (ai_model='<ai_model>' topn=<integer>) ] [ rich ] [ use cache ]` <br>
<span style="color: #ccc">|</span>    `rxn predict topn reactions from file '<filename.csv>' [ USING (ai_model='<ai_model>' topn=<integer>) ] [ rich ] [ use cache ]` <br>
<span style="color: #ccc">|</span>    `rxn predict topn reactions from dataframe <dataframe_name> [ USING (ai_model='<ai_model>' topn=<integer>) ] [ rich ] [ use cache ]` <br>

<span style="color: #d00">Not a valid command</span> <br>
<span style="color: #ccc">? set <br>
^</span> <br>

<span style="color: #dc0">You may want to try:</span> <br>

`?` <br>
<span style="color: #ccc">-</span> <br>
List all available commands. <br>

<span style="color: #ccc">Run `?` to list all command options.</span> <br>

<span style="color: #dc0">Commands starting with "set"</span> <br>
- `set workspace <workspace_name>` <br>
- `set context <toolkit_name> [ reset ]` <br>
- `set llm  <language_model_name>` <br>

Output()

<span style="color: #d00">Unknown error</span> <br>
<span style="color: #ccc">expected string or bytes-like object, got 'Markdown'</span> <br>

<span style="color: #090">Molecule <span style="color: #dc0">PROPANE</span> was added</span> <br>

<span style="color: #dc0">Add molecule <span style="color: #090">dopamine</span> to your molecule working set?</span> <br>

(y/n):  y

<span style="color: #090">Molecule <span style="color: #dc0">dopamine</span> was added</span> <br>

<span style="color: #dc0">Remove molecule <span style="color: #090">PROPANE</span> CCC from your working set?</span> <br>

(y/n):  y

<span style="color: #090">Molecule <span style="color: #dc0">PROPANE</span> was removed</span> <br>

,name,inchi,inchikey,canonical_smiles,isomeric_smiles,molecular_formula,cid
0,dopamine,"InChI=1S/C8H11NO2/c9-4-3-6-1-2-7(10)8(11)5-6/h1-2,5,10-11H,3-4,9H2",VYFYYTLLBUKUHU-UHFFFAOYSA-N,C1=CC(=C(C=C1CCN)O)O,C1=CC(=C(C=C1CCN)O)O,C8H11NO2,681

<span style="color: #ffa500">Analysis results were already empty</span> <br>

True

<span style="color: #090">Molecule successfully renamed</span> <br>

True

,name,inchi,inchikey,canonical_smiles,isomeric_smiles,molecular_formula,cid
0,dopamine_test,"InChI=1S/C8H11NO2/c9-4-3-6-1-2-7(10)8(11)5-6/h1-2,5,10-11H,3-4,9H2",VYFYYTLLBUKUHU-UHFFFAOYSA-N,C1=CC(=C(C=C1CCN)O)O,C1=CC(=C(C=C1CCN)O)O,C8H11NO2,681

<span style="color: #d00">Unable to load SDF file</span> <br>
<span style="color: #ccc">File error: Bad input file /Users/themoenen/Local/GitHub/openad/tests/_for_testing/tests/_for_testing/test_files/base_molecules.sdf</span> <br>

<span style="color: #090">Result set saved to workspace as <span style="color: #dc0">delete-me.csv</span></span> <br>

<span style="color: #dc0">Clear the molecule working set?</span> <br>

(y/n):  y

<span style="color: #090">Molecule working set was cleared</span> <br>

<span style="color: #ffa500">Permanently deleting file:</span> <br>
<span style="color: #ccc">/Users/themoenen/.openad/workspaces/DEFAULT/delete-me.csv</span> <br>

<span style="color: #dc0">Continue?</span> <br>

(y/n):  y

<span style="color: #090">File removed from workspace</span> <br>
<span style="color: #ccc">delete-me.csv</span> <br>

<span style="color: #dc0">Recording started</span> <br>
Run any number of commands and end with `save run as <run_name>` <br>

<span style="color: #d00">No `create run` found in history</span> <br>

<span style="color: #d00">Unknown error</span> <br>
<span style="color: #ccc">[Errno 2] No such file or directory: '/Users/themoenen/.openad/workspaces/DEFAULT/_runs/test_run.run'</span> <br>

<span style="color: #d00">No run named "test_run" found</span> <br>
<span style="color: #ccc">To see available runs, run `list runs`</span> <br>

<span style="color: #d00">The selected file <span style="color: #dc0">/Users/themoenen/Local/GitHub/openad/tests/_for_testing/tests/_for_testing/test_files/base_molecules.sdf</span> does not exist</span> <br>

Output()

True

True

True

44.10 <br>

{'identifiers': {'name': 'dopamine',
  'inchi': 'InChI=1S/C8H11NO2/c9-4-3-6-1-2-7(10)8(11)5-6/h1-2,5,10-11H,3-4,9H2',
  'inchikey': 'VYFYYTLLBUKUHU-UHFFFAOYSA-N',
  'canonical_smiles': 'C1=CC(=C(C=C1CCN)O)O',
  'isomeric_smiles': 'C1=CC(=C(C=C1CCN)O)O',
  'molecular_formula': 'C8H11NO2',
  'cid': 681},
 'synonyms': ['dopamine',
  '4-(2-Aminoethyl)benzene-1,2-diol',
  '51-61-6',
  '3-Hydroxytyramine',
  'Oxytyramine',
  'Hydroxytyramin',
  'Dopamin',
  '3,4-dihydroxyphenethylamine',
  'hydroxytyramine',
  '4-(2-Aminoethyl)catechol',
  '2-(3,4-dihydroxyphenyl)ethylamine',
  'Dopamina',
  'Dopaminum',
  '4-(2-Aminoethyl)pyrocatechol',
  '3,4-Dihydroxyphenylethylamine',
  '4-(2-Aminoethyl)-1,2-benzenediol',
  'ASL 279',
  'Pyrocatechol, 4-(2-aminoethyl)-',
  '1,2-Benzenediol, 4-(2-aminoethyl)-',
  'Dopaminum [INN-Latin]',
  'Dopamina [INN-Spanish]',
  'Dobutamine a',
  'A-dopamine',
  'KW-3-060',
  'NSC 173182',
  'HSDB 3068',
  'UNII-VTD58H1Z2X',
  'EINECS 200-110-0',
  'VTD58H1Z2X',
  'NSC-173182',
  'DTXSID6022420',
  'CHEBI:18243',
  'DTXCID602420',
  '3,4 Dihydroxyphenethylamine',
  'Dopaminum (INN-Latin)',
  'Dopamina (INN-Spanish)',
  'NORADRENALINE TARTRATE IMPURITY C (EP IMPURITY)',
  'NORADRENALINE TARTRATE IMPURITY C [EP IMPURITY]',
  'DOBUTAMINE HYDROCHLORIDESPECIFIED IMPURITY A (EP IMPURITY)',
  'DOBUTAMINE HYDROCHLORIDESPECIFIED IMPURITY A [EP IMPURITY]',
  'Dopamine1515',
  '200-110-0',
  'medopa',
  'intropin',
  'Dophamine',
  'L-DOPAMINE',
  '3-Hydroxtyramine',
  'alpha-(3,4-Dihydroxyphenyl)-beta-aminoethane',
  '4-(2-aminoethyl)-pyrocatechol',
  'Dopamine (INN)',
  'a-(3,4-Dihydroxyphenyl)-b-aminoethane',
  '4-(2-Aminoethyl)-1,2-bezenediol',
  '50444-17-2',
  'Revimine',
  'LDP',
  'NCGC00015519-05',
  'Pyrocatechol, 4-(2-aminoethyl)- (8CI)',
  'DOPAMINE [INN]',
  'Dopamine [INN:BAN]',
  '.alpha.-(3,4-Dihydroxyphenyl)-.beta.-aminoethane',
  '(3H)-Dopamine',
  'Pyrocatechol, 4-(2-aminoethyl)-, hydrochloride',
  '62-31-7 (HYDROCHLORIDE)',
  'CAS-51-61-6',
  'Medopa (TN)',
  'NSC169105',
  '1,2-Benzenediol, 4-(2-aminoethyl)- (9CI)',
  'Intropin [*hydrochloride*]',
  '4-(2-Aminoethyl)-1,2-benzenediol hydrochloride',
  '4-(2-aminoethyl)benzene-1,2-diol;hydrochloride',
  'SR-01000075366',
  '.beta.-(3,4-Dihydroxyphenyl)ethylamine hydrochloride',
  'm-Hydroxytyramine-',
  'Dopamine (USAN)(*hydrochloride*)',
  'IP 498',
  'MFCD00130258',
  'Intropin (Salt/Mix)',
  'Spectrum_001012',
  '1,2-Benzenediol, 4-(2-aminoethyl)-, labeled with tritium',
  'DOPAMINE [HSDB]',
  'DOPAMINE [MI]',
  'CHEMBL59',
  'DOPAMINE [VANDF]',
  'Spectrum2_001023',
  'Spectrum3_000406',
  'Spectrum4_000525',
  'Spectrum5_000945',
  'Lopac-H-8502',
  'Biomol-NT_000001',
  'bmse000909',
  'bmse000933',
  'DOPAMINE [WHO-DD]',
  'SCHEMBL8505',
  '1, 4-(2-aminoethyl)-',
  'Lopac0_000586',
  'Oprea1_088821',
  'BSPBio_001932',
  'GTPL940',
  'KBioGR_001129',
  'KBioGR_002388',
  'KBioGR_002484',
  'KBioSS_001492',
  'KBioSS_002393',
  'KBioSS_002491',
  'cid_65340',
  'BIDD:ER0506',
  'DivK1c_000780',
  'SPECTRUM1505155',
  'SPBio_001205',
  'BPBio1_001123',
  '153C5321-5FEE-4B0B-8925-F388F0EEEBD1',
  'BDBM55121',
  'KBio1_000780',
  'KBio2_001492',
  'KBio2_002388',
  'KBio2_002484',
  'KBio2_004060',
  'KBio2_004956',
  'KBio2_005052',
  'KBio2_006628',
  'KBio2_007524',
  'KBio2_007620',
  'KBio3_001152',
  'KBio3_002867',
  'KBio3_002962',
  'cMAP_000036',
  'cMAP_000065',
  'NINDS_000780',
  'HMS3743I03',
  'BCP34189',
  'Tox21_110167',
  '2-(3, 4-Dihydroxyphenyl)ethylamine',
  '2-(3,4-dihydroxyphenyl) ethylamine',
  'BBL013043',
  'STK301601',
  '3,4-DihydroxyphenylA currencythylamin',
  'AKOS003790978',
  'Tox21_110167_1',
  'CCG-204675',
  'DB00988',
  'FS-5341',
  'MSK000570-100M',
  'SDCCGSBI-0050568.P005',
  '2-(3,4-Dihydroxyphenyl)-1-ethanamine',
  '4-(2-Amino-ethyl)-benzene-1,2-diol',
  '4-(2-Aminoethyl)-1,2-benzenediol #',
  'IDI1_000780',
  'UPCMLD0ENAT5885989:001',
  'NCGC00015519-01',
  'NCGC00015519-02',
  'NCGC00015519-03',
  'NCGC00015519-04',
  'NCGC00015519-07',
  'NCGC00015519-08',
  'NCGC00015519-09',
  'NCGC00015519-10',
  'NCGC00015519-11',
  'NCGC00015519-13',
  'NCGC00015519-25',
  'NCGC00096050-01',
  'NCGC00096050-02',
  'NCGC00096050-03',
  'NCGC00096050-04',
  'NCGC00096050-05',
  'BP-23276',
  'Dopamine Solution in Methanol, 100ug/mL',
  '4-(2-aminoethyl)pyrocatechol;hydrochloride',
  'SBI-0050568.P004',
  'benzene, 1-(2-amino)ethyl-3,4-dihydroxy-',
  'NS00000608',
  'EN300-35022',
  'C03758',
  'D07870',
  'F21485',
  '4-(2-azanylethyl)benzene-1,2-diol;hydrochloride',
  'AB00053463-12',
  'AB00053463_13',
  'AB00053463_14',
  'L000232',
  'Q170304',
  'SR-01000075366-7',
  'BRD-K43887077-003-25-5',
  'BRD-K43887077-003-26-3',
  'BRD-K43887077-003-27-1',
  'DOBUTAMINE HYDROCHLORIDE IMPURITY A [EP IMPURITY]',
  'Oseltamivir-d3;Hydroxytyramin;4-(2-Aminoethyl)benzene-1,2-diol',
  '86389-83-5'],
 'properties': {'atom_stereo_count': 0,
  'atoms': [{'aid': 1, 'number': 8, 'element': 'O', 'x': 4.269, 'y': 2.405},
   {'aid': 2, 'number': 8, 'element': 'O', 'x': 2.5369, 'y': 1.405},
   {'aid': 3, 'number': 7, 'element': 'N', 'x': 6.8671, 'y': -2.095},
   {'aid': 4, 'number': 6, 'element': 'C', 'x': 6.001, 'y': -0.595},
   {'aid': 5, 'number': 6, 'element': 'C', 'x': 5.135, 'y': -0.095},
   {'aid': 6, 'number': 6, 'element': 'C', 'x': 6.001, 'y': -1.595},
   {'aid': 7, 'number': 6, 'element': 'C', 'x': 5.135, 'y': 0.905},
   {'aid': 8, 'number': 6, 'element': 'C', 'x': 4.269, 'y': -0.595},
   {'aid': 9, 'number': 6, 'element': 'C', 'x': 4.269, 'y': 1.405},
   {'aid': 10, 'number': 6, 'element': 'C', 'x': 3.403, 'y': -0.095},
   {'aid': 11, 'number': 6, 'element': 'C', 'x': 3.403, 'y': 0.905},
   {'aid': 12, 'number': 1, 'element': 'H', 'x': 6.6116, 'y': -0.7027},
   {'aid': 13, 'number': 1, 'element': 'H', 'x': 6.2131, 'y': -0.0124},
   {'aid': 14, 'number': 1, 'element': 'H', 'x': 5.3905, 'y': -1.4873},
   {'aid': 15, 'number': 1, 'element': 'H', 'x': 5.789, 'y': -2.1776},
   {'aid': 16, 'number': 1, 'element': 'H', 'x': 5.672, 'y': 1.215},
   {'aid': 17, 'number': 1, 'element': 'H', 'x': 4.269, 'y': -1.215},
   {'aid': 18, 'number': 1, 'element': 'H', 'x': 2.866, 'y': -0.405},
   {'aid': 19, 'number': 1, 'element': 'H', 'x': 6.8671, 'y': -2.715},
   {'aid': 20, 'number': 1, 'element': 'H', 'x': 7.404, 'y': -1.785},
   {'aid': 21, 'number': 1, 'element': 'H', 'x': 4.8059, 'y': 2.715},
   {'aid': 22, 'number': 1, 'element': 'H', 'x': 2, 'y': 1.095}],
  'bond_stereo_count': 0,
  'bonds': [{'aid1': 1, 'aid2': 9, 'order': 1},
   {'aid1': 1, 'aid2': 21, 'order': 1},
   {'aid1': 2, 'aid2': 11, 'order': 1},
   {'aid1': 2, 'aid2': 22, 'order': 1},
   {'aid1': 3, 'aid2': 6, 'order': 1},
   {'aid1': 3, 'aid2': 19, 'order': 1},
   {'aid1': 3, 'aid2': 20, 'order': 1},
   {'aid1': 4, 'aid2': 5, 'order': 1},
   {'aid1': 4, 'aid2': 6, 'order': 1},
   {'aid1': 4, 'aid2': 12, 'order': 1},
   {'aid1': 4, 'aid2': 13, 'order': 1},
   {'aid1': 5, 'aid2': 7, 'order': 2, 'style': 8},
   {'aid1': 5, 'aid2': 8, 'order': 1, 'style': 8},
   {'aid1': 6, 'aid2': 14, 'order': 1},
   {'aid1': 6, 'aid2': 15, 'order': 1},
   {'aid1': 7, 'aid2': 9, 'order': 1, 'style': 8},
   {'aid1': 7, 'aid2': 16, 'order': 1},
   {'aid1': 8, 'aid2': 10, 'order': 2, 'style': 8},
   {'aid1': 8, 'aid2': 17, 'order': 1},
   {'aid1': 9, 'aid2': 11, 'order': 2, 'style': 8},
   {'aid1': 10, 'aid2': 11, 'order': 1, 'style': 8},
   {'aid1': 10, 'aid2': 18, 'order': 1}],
  'cactvs_fingerprint': '11000000011100100011000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001100000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000001111000000000000100000000100000000000000000000000110000000100110000011001100000000100001100000000011010000000010000000000001000000000100000000000001000100000010000100000000000000000000000100000000000000000001000000010000000000000000010001000100010000000000001101000100010001000000010010010011000100010100000101001000100010011100000000111000000000001001001001101000000010001000010011001100000000111100100001101000010110000000011100010000000000000000000010000000000000000000000000100000000000000010000000000000000000010000000000000000000000000100000000000000000000000000000000000000000000000000000000',
  'charge': 0,
  'complexity': 119,
  'conformer_id_3d': None,
  'conformer_rmsd_3d': None,
  'coordinate_type': '2d',
  'covalent_unit_count': 1,
  'defined_atom_stereo_count': 0,
  'defined_bond_stereo_count': 0,
  'effective_rotor_count_3d': None,
  'elements': ['O',
   'O',
   'N',
   'C',
   'C',
   'C',
   'C',
   'C',
   'C',
   'C',
   'C',
   'H',
   'H',
   'H',
   'H',
   'H',
   'H',
   'H',
   'H',
   'H',
   'H',
   'H'],
  'exact_mass': '153.078978594',
  'feature_selfoverlap_3d': None,
  'fingerprint': '00000371C0723000000000000000000000000000000000000000300000000000000000010000001E00100800000C04C1980430068040020080022042000002000020200008888006888809262282911380700124D01109980790D0B00E20000100000040004000020000008000000000000000',
  'h_bond_acceptor_count': 3,
  'h_bond_donor_count': 3,
  'heavy_atom_count': 11,
  'isotope_atom_count': 0,
  'iupac_name': '4-(2-aminoethyl)benzene-1,2-diol',
  'mmff94_energy_3d': None,
  'mmff94_partial_charges_3d': None,
  'molecular_weight': '153.18',
  'monoisotopic_mass': '153.078978594',
  'multipoles_3d': None,
  'pharmacophore_features_3d': None,
  'record': {'id': {'id': {'cid': 681}},
   'atoms': {'aid': [1,
     2,
     3,
     4,
     5,
     6,
     7,
     8,
     9,
     10,
     11,
     12,
     13,
     14,
     15,
     16,
     17,
     18,
     19,
     20,
     21,
     22],
    'element': [8,
     8,
     7,
     6,
     6,
     6,
     6,
     6,
     6,
     6,
     6,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1]},
   'bonds': {'aid1': [1,
     1,
     2,
     2,
     3,
     3,
     3,
     4,
     4,
     4,
     4,
     5,
     5,
     6,
     6,
     7,
     7,
     8,
     8,
     9,
     10,
     10],
    'aid2': [9,
     21,
     11,
     22,
     6,
     19,
     20,
     5,
     6,
     12,
     13,
     7,
     8,
     14,
     15,
     9,
     16,
     10,
     17,
     11,
     11,
     18],
    'order': [1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     1,
     2,
     1,
     1,
     1,
     1,
     1,
     2,
     1,
     2,
     1,
     1]},
   'coords': [{'type': [1, 5, 255],
     'aid': [1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10,
      11,
      12,
      13,
      14,
      15,
      16,
      17,
      18,
      19,
      20,
      21,
      22],
     'conformers': [{'x': [4.269,
        2.5369,
        6.8671,
        6.001,
        5.135,
        6.001,
        5.135,
        4.269,
        4.269,
        3.403,
        3.403,
        6.6116,
        6.2131,
        5.3905,
        5.789,
        5.672,
        4.269,
        2.866,
        6.8671,
        7.404,
        4.8059,
        2],
       'y': [2.405,
        1.405,
        -2.095,
        -0.595,
        -0.095,
        -1.595,
        0.905,
        -0.595,
        1.405,
        -0.095,
        0.905,
        -0.7027,
        -0.0124,
        -1.4873,
        -2.1776,
        1.215,
        -1.215,
        -0.405,
        -2.715,
        -1.785,
        2.715,
        1.095],
       'style': {'annotation': [8, 8, 8, 8, 8, 8],
        'aid1': [5, 5, 7, 8, 9, 10],
        'aid2': [7, 8, 9, 10, 11, 11]}}]}],
   'charge': 0,
   'props': [{'urn': {'label': 'Compound',
      'name': 'Canonicalized',
      'datatype': 5,
      'release': '2025.04.14'},
     'value': {'ival': 1}},
    {'urn': {'label': 'Compound Complexity',
      'datatype': 7,
      'implementation': 'E_COMPLEXITY',
      'version': '3.4.8.18',
      'software': 'Cactvs',
      'source': 'Xemistry GmbH',
      'release': '2025.04.14'},
     'value': {'fval': 119}},
    {'urn': {'label': 'Count',
      'name': 'Hydrogen Bond Acceptor',
      'datatype': 5,
      'implementation': 'E_NHACCEPTORS',
      'version': '3.4.8.18',
      'software': 'Cactvs',
      'source': 'Xemistry GmbH',
      'release': '2025.04.14'},
     'value': {'ival': 3}},
    {'urn': {'label': 'Count',
      'name': 'Hydrogen Bond Donor',
      'datatype': 5,
      'implementation': 'E_NHDONORS',
      'version': '3.4.8.18',
      'software': 'Cactvs',
      'source': 'Xemistry GmbH',
      'release': '2025.04.14'},
     'value': {'ival': 3}},
    {'urn': {'label': 'Count',
      'name': 'Rotatable Bond',
      'datatype': 5,
      'implementation': 'E_NROTBONDS',
      'version': '3.4.8.18',
      'software': 'Cactvs',
      'source': 'Xemistry GmbH',
      'release': '2025.04.14'},
     'value': {'ival': 2}},
    {'urn': {'label': 'Fingerprint',
      'name': 'SubStructure Keys',
      'datatype': 16,
      'parameters': 'extended 2',
      'implementation': 'E_SCREEN',
      'version': '3.4.8.18',
      'software': 'Cactvs',
      'source': 'Xemistry GmbH',
      'release': '2025.04.14'},
     'value': {'binary': '00000371C0723000000000000000000000000000000000000000300000000000000000010000001E00100800000C04C1980430068040020080022042000002000020200008888006888809262282911380700124D01109980790D0B00E20000100000040004000020000008000000000000000'}},
    {'urn': {'label': 'IUPAC Name',
      'name': 'Allowed',
      'datatype': 1,
      'version': '2.7.0',
      'software': 'Lexichem TK',
      'source': 'OpenEye Scientific Software',
      'release': '2025.04.14'},
     'value': {'sval': '4-(2-aminoethyl)benzene-1,2-diol'}},
    {'urn': {'label': 'IUPAC Name',
      'name': 'CAS-like Style',
      'datatype': 1,
      'version': '2.7.0',
      'software': 'Lexichem TK',
      'source': 'OpenEye Scientific Software',
      'release': '2025.04.14'},
     'value': {'sval': '4-(2-aminoethyl)benzene-1,2-diol'}},
    {'urn': {'label': 'IUPAC Name',
      'name': 'Markup',
      'datatype': 1,
      'version': '2.7.0',
      'software': 'Lexichem TK',
      'source': 'OpenEye Scientific Software',
      'release': '2025.04.14'},
     'value': {'sval': '4-(2-aminoethyl)benzene-1,2-diol'}},
    {'urn': {'label': 'IUPAC Name',
      'name': 'Preferred',
      'datatype': 1,
      'version': '2.7.0',
      'software': 'Lexichem TK',
      'source': 'OpenEye Scientific Software',
      'release': '2025.04.14'},
     'value': {'sval': '4-(2-aminoethyl)benzene-1,2-diol'}},
    {'urn': {'label': 'IUPAC Name',
      'name': 'Systematic',
      'datatype': 1,
      'version': '2.7.0',
      'software': 'Lexichem TK',
      'source': 'OpenEye Scientific Software',
      'release': '2025.04.14'},
     'value': {'sval': '4-(2-azanylethyl)benzene-1,2-diol'}},
    {'urn': {'label': 'IUPAC Name',
      'name': 'Traditional',
      'datatype': 1,
      'version': '2.7.0',
      'software': 'Lexichem TK',
      'source': 'OpenEye Scientific Software',
      'release': '2025.04.14'},
     'value': {'sval': '4-(2-aminoethyl)pyrocatechol'}},
    {'urn': {'label': 'InChI',
      'name': 'Standard',
      'datatype': 1,
      'version': '1.07.2',
      'software': 'InChI',
      'source': 'iupac.org',
      'release': '2025.04.14'},
     'value': {'sval': 'InChI=1S/C8H11NO2/c9-4-3-6-1-2-7(10)8(11)5-6/h1-2,5,10-11H,3-4,9H2'}},
    {'urn': {'label': 'InChIKey',
      'name': 'Standard',
      'datatype': 1,
      'version': '1.07.2',
      'software': 'InChI',
      'source': 'iupac.org',
      'release': '2025.04.14'},
     'value': {'sval': 'VYFYYTLLBUKUHU-UHFFFAOYSA-N'}},
    {'urn': {'label': 'Log P',
      'name': 'XLogP3',
      'datatype': 7,
      'version': '3.0',
      'source': 'sioc-ccbg.ac.cn',
      'release': '2025.04.14'},
     'value': {'fval': -1}},
    {'urn': {'label': 'Mass',
      'name': 'Exact',
      'datatype': 1,
      'version': '2.2',
      'software': 'PubChem',
      'source': 'ncbi.nlm.nih.gov',
      'release': '2025.04.14'},
     'value': {'sval': '153.078978594'}},
    {'urn': {'label': 'Molecular Formula',
      'datatype': 1,
      'version': '2.2',
      'software': 'PubChem',
      'source': 'ncbi.nlm.nih.gov',
      'release': '2025.04.14'},
     'value': {'sval': 'C8H11NO2'}},
    {'urn': {'label': 'Molecular Weight',
      'datatype': 1,
      'version': '2.2',
      'software': 'PubChem',
      'source': 'ncbi.nlm.nih.gov',
      'release': '2025.04.14'},
     'value': {'sval': '153.18'}},
    {'urn': {'label': 'ReferenceStandardization',
      'name': 'Structure',
      'datatype': 1,
      'version': '2.2',
      'software': 'PubChem',
      'source': 'ncbi.nlm.nih.gov',
      'release': '2025.04.14'},
     'value': {'sval': 'Bypass - this structure was created from CID 71564'}},
    {'urn': {'label': 'SMILES',
      'name': 'Absolute',
      'datatype': 1,
      'version': '2.3.0',
      'software': 'OEChem',
      'source': 'OpenEye Scientific Software',
      'release': '2025.04.14'},
     'value': {'sval': 'C1=CC(=C(C=C1CCN)O)O'}},
    {'urn': {'label': 'SMILES',
      'name': 'Canonical',
      'datatype': 1,
      'version': '2.3.0',
      'software': 'OEChem',
      'source': 'OpenEye Scientific Software',
      'release': '2025.04.14'},
     'value': {'sval': 'C1=CC(=C(C=C1CCN)O)O'}},
    {'urn': {'label': 'SMILES',
      'name': 'Isomeric',
      'datatype': 1,
      'version': '2.3.0',
      'software': 'OEChem',
      'source': 'OpenEye Scientific Software',
      'release': '2025.04.14'},
     'value': {'sval': 'C1=CC(=C(C=C1CCN)O)O'}},
    {'urn': {'label': 'Topological',
      'name': 'Polar Surface Area',
      'datatype': 7,
      'implementation': 'E_TPSA',
      'version': '3.4.8.18',
      'software': 'Cactvs',
      'source': 'Xemistry GmbH',
      'release': '2025.04.14'},
     'value': {'fval': 66.5}},
    {'urn': {'label': 'Weight',
      'name': 'MonoIsotopic',
      'datatype': 1,
      'version': '2.2',
      'software': 'PubChem',
      'source': 'ncbi.nlm.nih.gov',
      'release': '2025.04.14'},
     'value': {'sval': '153.078978594'}}],
   'count': {'heavy_atom': 11,
    'atom_chiral': 0,
    'atom_chiral_def': 0,
    'atom_chiral_undef': 0,
    'bond_chiral': 0,
    'bond_chiral_def': 0,
    'bond_chiral_undef': 0,
    'isotope_atom': 0,
    'covalent_unit': 1,
    'tautomers': -1}},
  'rotatable_bond_count': 2,
  'shape_fingerprint_3d': None,
  'shape_selfoverlap_3d': None,
  'tpsa': 66.5,
  'undefined_atom_stereo_count': 0,
  'undefined_bond_stereo_count': 0,
  'volume_3d': None,
  'xlogp': -1},
 'property_sources': {'atom_stereo_count': {'source': 'PubChem'},
  'bond_stereo_count': {'source': 'PubChem'},
  'canonical_smiles': {'label': 'SMILES',
   'name': 'Canonical',
   'datatype': 1,
   'version': '2.3.0',
   'software': 'OEChem',
   'source': 'OpenEye Scientific Software',
   'release': '2025.04.14'},
  'charge': {'source': 'PubChem'},
  'cid': {'source': 'PubChem'},
  'complexity': {'label': 'Compound',
   'name': 'Canonicalized',
   'datatype': 5,
   'release': '2025.04.14'},
  'conformer_count_3d': {'source': 'PubChem'},
  'conformer_id_3d': {'source': 'PubChem'},
  'conformer_model_rmsd_3d': {'source': 'PubChem'},
  'conformer_rmsd_3d': {'source': 'PubChem'},
  'coordinate_type': {'source': 'PubChem'},
  'covalent_unit_count': {'source': 'PubChem'},
  'defined_atom_stereo_count': {'source': 'PubChem'},
  'defined_bond_stereo_count': {'source': 'PubChem'},
  'effective_rotor_count_3d': {'source': 'PubChem'},
  'exact_mass': {'label': 'Mass',
   'name': 'Exact',
   'datatype': 1,
   'version': '2.2',
   'software': 'PubChem',
   'source': 'ncbi.nlm.nih.gov',
   'release': '2025.04.14'},
  'feature_acceptor_count_3d': {'source': 'PubChem'},
  'feature_anion_count_3d': {'source': 'PubChem'},
  'feature_cation_count_3d': {'source': 'PubChem'},
  'feature_count_3d': {'source': 'PubChem'},
  'feature_donor_count_3d': {'source': 'PubChem'},

<span style="color: #d00">The selected file <span style="color: #dc0">/Users/themoenen/Local/GitHub/openad/tests/_for_testing/tests/_for_testing/test_files/sample.csv</span> does not exist</span> <br>

<span style="color: #ccc">Next up, you can run: </span>`result open`/`edit`/`copy`/`display`/`as dataframe`/`save [as '<filename.csv>']` <br>

<span style="color: #dc0">The destination file already exists, overwrite?</span> <br>

(y/n):  y

<span style="color: #090">Result saved to workspace as <span style="color: #dc0">sample_copy.csv</span></span> <br>

Filename:  y

<span style="color: #090">Result saved to workspace as <span style="color: #dc0">y.csv</span></span> <br>

<span style="color: #090">Data copied to clipboard</span> <br>

<span style="color: #ccc">Next up, you can run: </span>`result open`/`edit`/`copy`/`display`/`as dataframe`/`save [as '<filename.csv>']` <br>

<span style="color: #d00">The selected file <span style="color: #dc0">./tests/_for_testing/test_files/sample_config.json</span> does not exist</span> <br>

<span style="color: #d00">The selected file <span style="color: #dc0">./tests/_for_testing/test_files/sample_config-schema.json</span> does not exist</span> <br>

<span style="color: #d00">Not a valid command</span> <br>
<span style="color: #ccc">edit config 'sample_config.json' <br>
^</span> <br>

<span style="color: #dc0">Commands starting with "e"</span> <br>
- `export molecule|mol <name> | <smiles> | <inchi> | <inchikey> | <cid> [ as file ]` <br>
- `enrich molecules|mols with analysis` <br>
- `export molecules|mols [ as '<filename.molset.json|sdf|csv|smi>' ]` <br>

<span style="color: #ccc">Run `?` to list all command options.</span> <br>

<span style="color: #d00">Not a valid command</span> <br>
<span style="color: #ccc">edit config 'sample_config.json' schema 'sample_config-schema.json' <br>
^</span> <br>

<span style="color: #dc0">Commands starting with "e"</span> <br>
- `export molecule|mol <name> | <smiles> | <inchi> | <inchikey> | <cid> [ as file ]` <br>
- `enrich molecules|mols with analysis` <br>
- `export molecules|mols [ as '<filename.molset.json|sdf|csv|smi>' ]` <br>

<span style="color: #ccc">Run `?` to list all command options.</span> <br>

<span style="color: #ccc">To see what you can do with a workspace, run `? workspace`.</span> <br>

<span style="color: #d00">The workspace <span style="color: #dc0">KEEPER</span> does not exist</span> <br>

<span style="color: #ccc">To see what you can do with a workspace, run `? workspace`.</span> <br>

Workspace description:  y

Output()

Output()

<span style="color: #ccc">To see what you can do with a workspace, run `? workspace`.</span> <br>

Workspace description:  y

Output()

Output()

<span style="color: #ccc">To see what you can do with a workspace, run `? workspace`.</span> <br>

<span style="color: #ccc">Active workspace:</span> <br>
<span style="color: #dc0">TEST_WORKSPACE</span> <br>
y <br>

<span style="color: #090">You successfully set your workspace to <span style="color: #dc0">DEFAULT</span></span> <br>

<span style="color: #dc0">TEST_WORKSPACE</span> <br>
y <br>

<span style="color: #090">Workspace <span style="color: #dc0">TEST_WORKSPACE</span> successfully removed</span> <br>

<span style="color: #ccc">To see what you can do with a workspace, run `? workspace`.</span> <br>